version: '3.8'

services:
  mongodb:
    image: mongo:6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - release-tracker-network

  release-tracker:
    build: .
    restart: always
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/dnio-release-tracker
      - BASE_PATH=/release-tracker
      - JIRA_BASE_URL=${JIRA_BASE_URL:-https://appveen.atlassian.net}
      - JIRA_API_VERSION=${JIRA_API_VERSION:-3}
      - JIRA_EMAIL=${JIRA_EMAIL:-}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN:-}
    depends_on:
      - mongodb
    networks:
      - release-tracker-network

volumes:
  mongodb_data:

networks:
  release-tracker-network:
    driver: bridge
